DELIMITER $$
CREATE
    FUNCTION `sga2018`.`fn_Edad`(_fecha DATETIME)
    RETURNS INT DETERMINISTIC
    BEGIN
	DECLARE _edad INT DEFAULT 0;
	SET _edad = (SELECT TIMESTAMPDIFF(YEAR,_fecha,CURDATE()));
	RETURN _edad;
    END$$

DELIMITER ;